apiVersion: v1
kind: Template
metadata:
  name: decisionserver-nexus-persistent
labels:
  template: decisionserver-nexus-persistent
  group: decisionserver
metadata:
  annotations:
    description: Creates a persistent Nexus Repository
    tags: instant-app,nexus,decisionserver
  name: decisionserver-nexus-persistent
parameters:
- description: Nexus Repository service name
  name: APPLICATION_NAME
  value: nexus
- description: Volume space available for data, e.g. 512Mi, 2Gi
  name: VOLUME_CAPACITY
  required: true
  value: 512Mi
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APPLICATION_NAME}-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Sonatype Nexus repository manager's http port
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: ${APPLICATION_NAME}
